
<h3>Who made this website?</h3>
<p>This website was made by members of <a href="http://www.team1735.org/">FIRST Robotics Team 1735, The Green Reapers, from Worcester, MA</a>. </p>

<h3>Why did you make this website?</h3>
<p>In today's world there are more options than ever before to build a robot. 
This has created an opportunity for roboticists to build ever more complex designs quicker. 
All this diversity has created a problem in finding just the right part. 
This website aims to help this problem by making it easy to narrow down exactly what you need.</p>

<h3>Can you list price?</h3>
<p>We decided not to list price because this can change and might vary from vendor to vendor.</p>

<h3>Why isn't XYZ listed? Can you add it?</h3>
<p>There is a very good chance we missed adding a product or missed a spec. Do not take it personally, we make mistakes. 
Here is why it might have been missed or why there is a mistake:</p>
<ul>
	<li>If the product has various versions we grouped them into one.</li>
	<li>In some cases we could not find a location to buy the product so we did not list it. An example of this would be a Van Door or Window motor.</li>
	<li>There are a lot of products and specs, we could have missed it.</li>
	<li>The Mountain Dew from the late nights may not have kicked in by time we looked into your product.</li>
</ul>
<p>If you think the missing product or the mistake you found is still a mistake please update this <a href="https://docs.google.com/spreadsheets/d/1wNkNvcVklXsYa0dGmGmAiwMzYg4DSsCbknDMIBcHobQ/edit?usp=sharing" target="_blank">Google Spreadsheet</a>. We will review it and update the site.</p>

<h3>How can I make a suggestion for your website?</h3>
<p>Do you have a great idea for a new category or a new facet to search off of? Please email us at <a href="mailto:parts@findrobotparts.com">parts@findrobotparts.com</a> and we will see what we can do.</p>
