</head>

<body>

	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<a class="navbar-brand" href="/">
			<img src="http://findrobotparts.com/images/find-robot-parts.png" alt="Find Robot Parts" title="Find Robot Parts" width="220" height="33" class="d-inline-block align-top">
		</a>
		<button type="button" class="navbar-toggler collapsed ml-auto" data-toggle="collapse" data-target="#sidebar" id="filterbutton">
			<span class="fas fa-filter"></span>
		</button>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbar">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">3D</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="/3d/battery-accessories/">Battery Accessories</a>
						<a class="dropdown-item" href="/3d/motor-adaptors/">Motor Adaptors</a>
						<a class="dropdown-item" href="/3d/mounts/">Mounts</a>
						<a class="dropdown-item" href="/3d/wheels/">Wheels</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Electrical</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="/batteries/">Batteries</a>
						<a class="dropdown-item" href="/battery-chargers/">Battery Chargers</a>
						<a class="dropdown-item" href="/gamecontrollers/">Game Controllers</a>
						<a class="dropdown-item" href="/lights/">Lights</a>
						<a class="dropdown-item" href="/motor-controllers/">Motor Controllers</a>
						<a class="dropdown-item" href="/mxp-boards/">MXP Boards</a>
						<a class="dropdown-item" href="/sensors/">Sensors</a>
						<a class="dropdown-item" href="/wireconnectors/">Wire Connectors</a>
						<a class="dropdown-item" href="/vendors/categories/32/tags/330,333,334,335,336">Electrical Vendors</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Hardware</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="/bearings/">Bearings</a>
						<a class="dropdown-item" href="/gussets/">Gussets and Mounts</a>
						<a class="dropdown-item" href="/shafts/">Shafts</a>
						<a class="dropdown-item" href="/shaftcollars/">Shaft Collars</a>
						<a class="dropdown-item" href="/structure/">Structure</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Motion</a>
					<div class="dropdown-menu dropdown-menu-right">
							<a class="dropdown-item" href="/belts/">Belts</a>
							<a class="dropdown-item" href="/chain/">Chain</a>
							<a class="dropdown-item" href="/gearboxes/">Gearboxes</a>
							<a class="dropdown-item" href="/gears/">Gears</a>
							<a class="dropdown-item" href="/hubs/">Hubs</a>
							<a class="dropdown-item" href="/linearactuators/">Linear Actuators</a>
							<a class="dropdown-item" href="/motors/">Motors</a>
							<a class="dropdown-item" href="/pulleys/">Pulleys</a>
							<a class="dropdown-item" href="/servos/">Servos</a>
							<a class="dropdown-item" href="/sprockets/">Sprockets</a>
							<a class="dropdown-item" href="/wheels/">Wheels</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Pneumatics</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="/accumulators/">Accumulators</a>
						<a class="dropdown-item" href="/compressors/">Compressors</a>
						<a class="dropdown-item" href="/pneumaticfittings/">Pneumatic Fittings</a>
						<a class="dropdown-item" href="/pneumatictubing/">Pneumatic Tubing</a>
						<a class="dropdown-item" href="/vendors/categories/32/tags/325">Pneumatics Vendors</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Misc.</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="/bumperfabric/">Bumper Fabric</a>
						<a class="dropdown-item" href="/bumpernumbers/">Bumper Numbers</a>
						<a class="dropdown-item" href="/resources-programming/">Programming Resources</a>
						<a class="dropdown-item" href="/vendors/">Vendors</a>
					</div>
				</li>
				<li class="nav-item"><a class="nav-link" href="/questions/">FAQ</a></li>
			</ul>
		</div>
	</nav>

	<div class="container-fluid">
	  <div class="row">
		<nav class="col-md-2 d-md-block bg-light sidebar pt-4 collapse" id="sidebar">

