</head>

  <body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar" aria-expanded="false" aria-controls="navbar" id="filterbutton">
			<span class="sr-only">Filter</span>
			<span class="glyphicon glyphicon-filter"></span>
		  </button>
		  <a class="navbar-brand" href="/"><img src="/images/find-robot-parts.png" alt="Find Robot Parts" title="Find Robot Parts" width="220" height="33"></a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
		  <ul class="nav navbar-nav navbar-right">
		  	<li class="dropdown">
		  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">3D <span class="caret"></span></a>
		  		<ul class="dropdown-menu">
		  			<li><a href="/3d/battery-accessories/">Battery Accessories</a></li>
		  			<li><a href="/3d/motor-adaptors/">Motor Adaptors</a></li>
		  			<li><a href="/3d/mounts/">Mounts</a></li>
		  			<li><a href="/3d/wheels/">Wheels</a></li>
		  		</ul>
		  	</li>
		  	<li class="dropdown">
		  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Electrical <span class="caret"></span></a>
		  		<ul class="dropdown-menu">
					<li><a href="/batteries/">Batteries</a></li>
					<li><a href="/battery-chargers/">Battery Chargers</a></li>
					<li><a href="/gamecontrollers/">Game Controllers</a></li>
					<li><a href="/lights/">Lights</a></li>
					<li><a href="/motor-controllers/">Motor Controllers</a></li>
					<li><a href="/sensors/">Sensors</a></li>
					<li><a href="/wireconnectors/">Wire Connectors</a></li>
					<li><a href="/vendors/categories/32/tags/330,333,334,335,336">Electrical Vendors</a></li>
		  		</ul>
		  	</li>
		  	<li class="dropdown">
		  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Hardware <span class="caret"></span></a>
		  		<ul class="dropdown-menu">
		  			<li><a href="/bearings/">Bearings</a></li>
					<li><a href="/gussets/">Gussets and Mounts</a></li>
					<li><a href="/shafts/">Shafts</a></li>
		  			<li><a href="/shaftcollars/">Shaft Collars</a></li>
					<li><a href="/structure/">Structure</a></li>
		  		</ul>
		  	</li>
		  	<li class="dropdown">
		  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Motion <span class="caret"></span></a>
		  		<ul class="dropdown-menu">
	  					<li><a href="/belts/">Belts</a></li>
	  					<li><a href="/chain/">Chain</a></li>
	  					<li><a href="/gearboxes/">Gearboxes</a></li>
	  					<li><a href="/gears/">Gears</a></li>
	  					<li><a href="/hubs/">Hubs</a></li>
	  					<li><a href="/linearactuators/">Linear Actuators</a></li>
	  					<li><a href="/motors/">Motors</a></li>
	  					<li><a href="/pulleys/">Pulleys</a></li>
	  					<li><a href="/servos/">Servos</a></li>
	  					<li><a href="/sprockets/">Sprockets</a></li>
	  					<li><a href="/wheels/">Wheels</a></li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Pneumatics <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="/accumulators/">Accumulators</a></li>
					<li><a href="/compressors/">Compressors</a></li>
					<li><a href="/pneumaticfittings/">Pneumatic Fittings</a></li>
					<li><a href="/pneumatictubing/">Pneumatic Tubing</a></li>
					<li><a href="/vendors/categories/32/tags/325">Pneumatics Vendors</a></li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Misc. <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="/bumperfabric/">Bumper Fabric</a></li>
					<li><a href="/bumpernumbers/">Bumper Numbers</a></li>
	 				<li><a href="/vendors/">Vendors</a></li>
			   	</ul>
			</li>
			<li><a href="/questions/">FAQ</a></li>
		  </ul>
		</div>
	  </div>
	</nav>

	<div class="container-fluid">
	  <div class="row">
		<div class="col-sm-3 col-md-2 sidebar navbar-collapse" id="sidebar">
