	<h1 class="page-header">Select product</h1>
	<p>You can use Find Robot Parts to look for the part that will best fit your needs. We work to include as many products as possible.</p>
	
	<h2>3D Printable Models</h2>
	<div class="row placeholders">
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/3d/battery-accessories/" class="addcolor">
				<img src="/images/categories/3d-battery-accessory-gray.jpg" width="150" height="150" class="img-responsive gray" alt="3D Printed Battery Accessories">
				<img src="/images/categories/3d-battery-accessory-color.jpg" width="150" height="150" class="img-responsive color" alt="3D Printed Battery Accessories">
				<h4>Battery Accessories</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/3d/motor-adaptors/" class="addcolor">
				<img src="/images/categories/3d-motor-adaptor-gray.jpg" width="150" height="150" class="img-responsive gray" alt="3D Printed Motor Adaptors">
				<img src="/images/categories/3d-motor-adaptor-color.jpg" width="150" height="150" class="img-responsive color" alt="3D Printed Motor Adaptors">
				<h4>Motor Adaptors</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/3d/mounts/" class="addcolor">
				<img src="/images/categories/3d-mounts-gray.jpg" width="150" height="150" class="img-responsive gray" alt="3D Printed Mounts">
				<img src="/images/categories/3d-mounts-color.jpg" width="150" height="150" class="img-responsive color" alt="3D Printed Mounts">
				<h4>Mounts</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/3d/wheels/" class="addcolor">
				<img src="/images/categories/3d-wheel-gray.jpg" width="150" height="150" class="img-responsive gray" alt="3D Printed Wheels">
				<img src="/images/categories/3d-wheel-color.jpg" width="150" height="150" class="img-responsive color" alt="3D Printed Wheels">
				<h4>Wheels</h4>
			</a>
		</div>
	</div>	
	
	<h2>Electrical</h2>
	<div class="row placeholders">
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/batteries/" class="addcolor">
				<img src="/images/categories/battery-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Batteries">
				<img src="/images/categories/battery-color.jpg" width="150" height="150" class="img-responsive color" alt="Batteries">
				<h4>Batteries</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/battery-chargers/" class="addcolor">
				<img src="/images/categories/battery-charger-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Battery Chargers">
				<img src="/images/categories/battery-charger-color.jpg" width="150" height="150" class="img-responsive color" alt="Battery Chargers">
				<h4>Battery Chargers</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/gamecontrollers/" class="addcolor">
				<img src="/images/categories/gamecontroller-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Game Controllers">
				<img src="/images/categories/gamecontroller-color.jpg" width="150" height="150" class="img-responsive color" alt="Game Controllers">
				<h4>Game Controllers</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/lights/" class="addcolor">
				<img src="/images/categories/light-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Lights">
				<img src="/images/categories/light-color.jpg" width="150" height="150" class="img-responsive color" alt="Lights">
				<h4>Lights</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/motor-controllers/" class="addcolor">
				<img src="/images/categories/motor-controller-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Motor Controllers">
				<img src="/images/categories/motor-controller-color.jpg" width="150" height="150" class="img-responsive color" alt="Motor Controllers">
				<h4>Motor Controllers</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/mxp-boards/" class="addcolor">
				<img src="/images/categories/mxp-board-gray.jpg" width="150" height="150" class="img-responsive gray" alt="MXP Boards">
				<img src="/images/categories/mxp-board-color.jpg" width="150" height="150" class="img-responsive color" alt="MXP Boards">
				<h4>MXP Boards</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/sensors/" class="addcolor">
				<img src="/images/categories/sensor-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Sensors">
				<img src="/images/categories/sensor-color.jpg" width="150" height="150" class="img-responsive color" alt="Sensors">
				<h4>Sensors</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/wireconnectors/" class="addcolor">
				<img src="/images/categories/wireconnector-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Wire Connectors">
				<img src="/images/categories/wireconnector-color.jpg" width="150" height="150" class="img-responsive color" alt="Wire Connectors">
				<h4>Wire Connectors</h4>
			</a>
		</div>
	</div>

	<h2>Hardware</h2>
	<div class="row placeholders">
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/bearings/" class="addcolor">
				<img src="/images/categories/bearing-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Bearings">
				<img src="/images/categories/bearing-color.jpg" width="150" height="150" class="img-responsive color" alt="Bearings">
				<h4>Bearings</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/gussets/" class="addcolor">
				<img src="/images/categories/gusset-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Gussets and Mounts">
				<img src="/images/categories/gusset-color.jpg" width="150" height="150" class="img-responsive color" alt="Gussets and Mounts">
				<h4>Gussets and Mounts</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/shafts/" class="addcolor">
				<img src="/images/categories/shaft-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Shafts">
				<img src="/images/categories/shaft-color.jpg" width="150" height="150" class="img-responsive color" alt="Shafts">
				<h4>Shafts</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/shaftcollars/" class="addcolor">
				<img src="/images/categories/shaftcollar-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Shaft Collars">
				<img src="/images/categories/shaftcollar-color.jpg" width="150" height="150" class="img-responsive color" alt="Shaft Collars">
				<h4>Shaft Collars</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/structure/" class="addcolor">
				<img src="/images/categories/structure-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Structure">
				<img src="/images/categories/structure-color.jpg" width="150" height="150" class="img-responsive color" alt="Structure">
				<h4>Structure</h4>
			</a>
		</div>

	</div>

	
	<h2>Motion</h2>
	<div class="row placeholders">
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/belts/" class="addcolor">
				<img src="/images/categories/belt-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Belts">
				<img src="/images/categories/belt-color.jpg" width="150" height="150" class="img-responsive color" alt="Belts">
				<h4>Belts</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/chain/" class="addcolor">
				<img src="/images/categories/chain-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Chain">
				<img src="/images/categories/chain-color.jpg" width="150" height="150" class="img-responsive color" alt="Chain">
				<h4>Chain</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/gearboxes/" class="addcolor">
				<img src="/images/categories/gears-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Gearboxes">
				<img src="/images/categories/gears-color.jpg" width="150" height="150" class="img-responsive color" alt="Gearboxes">
				<h4>Gearboxes</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/gears/" class="addcolor">
				<img src="/images/categories/gear-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Gears">
				<img src="/images/categories/gear-color.jpg" width="150" height="150" class="img-responsive color" alt="Gears">
				<h4>Gears</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/hubs/" class="addcolor">
				<img src="/images/categories/hub-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Hubs">
				<img src="/images/categories/hub-color.jpg" width="150" height="150" class="img-responsive color" alt="Hubs">
				<h4>Hubs</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/linearactuators/" class="addcolor">
				<img src="/images/categories/linearactuator-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Linear Actuators">
				<img src="/images/categories/linearactuator-color.jpg" width="150" height="150" class="img-responsive color" alt="Linear Actuators">
				<h4>Linear Actuators</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/motors/" class="addcolor">
				<img src="/images/categories/motor-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Motors">
				<img src="/images/categories/motor-color.jpg" width="150" height="150" class="img-responsive color" alt="Motors">
				<h4>Motors</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/pulleys/" class="addcolor">
				<img src="/images/categories/pulley-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Pulleys">
				<img src="/images/categories/pulley-color.jpg" width="150" height="150" class="img-responsive color" alt="Pulleys">
				<h4>Pulleys</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/servos/" class="addcolor">
				<img src="/images/categories/servo-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Servos">
				<img src="/images/categories/servo-color.jpg" width="150" height="150" class="img-responsive color" alt="Servos">
				<h4>Servos</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/sprockets/" class="addcolor">
				<img src="/images/categories/sprocket-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Sprockets">
				<img src="/images/categories/sprocket-color.jpg" width="150" height="150" class="img-responsive color" alt="Sprockets">
				<h4>Sprockets</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/wheels/" class="addcolor">
				<img src="/images/categories/wheel-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Wheels">
				<img src="/images/categories/wheel-color.jpg" width="150" height="150" class="img-responsive color" alt="Wheels">
				<h4>Wheels</h4>
			</a>
		</div>
	</div>

	<h2>Pneumatics</h2>
	<div class="row placeholders">
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/accumulators/" class="addcolor">
				<img src="/images/categories/accumulator-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Accumulators">
				<img src="/images/categories/accumulator-color.jpg" width="150" height="150" class="img-responsive color" alt="Accumulators">
				<h4>Accumulators</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/compressors/" class="addcolor">
				<img src="/images/categories/compressor-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Compressors">
				<img src="/images/categories/compressor-color.jpg" width="150" height="150" class="img-responsive color" alt="Compressors">
				<h4>Compressors</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/pneumaticfittings/" class="addcolor">
				<img src="/images/categories/pneumaticfittings-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Pneumatic Fittings">
				<img src="/images/categories/pneumaticfittings-color.jpg" width="150" height="150" class="img-responsive color" alt="Pneumatic Fittings">
				<h4>Pneumatic Fittings</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/pneumatictubing/" class="addcolor">
				<img src="/images/categories/pneumatictubing-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Pneumatic Tubing">
				<img src="/images/categories/pneumatictubing-color.jpg" width="150" height="150" class="img-responsive color" alt="Pneumatic Tubing">
				<h4>Pneumatic Tubing</h4>
			</a>
		</div>
	</div>

	<h2>Miscellaneous</h2>
	<div class="row placeholders">
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/bumperfabric/" class="addcolor">
				<img src="/images/categories/bumperfabric-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Bumper Fabric">
				<img src="/images/categories/bumperfabric-color.jpg" width="150" height="150" class="img-responsive color" alt="Bumper Fabric">
				<h4>Bumper Fabric</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/bumpernumbers/" class="addcolor">
				<img src="/images/categories/bumpernumber-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Bumper Numbers">
				<img src="/images/categories/bumpernumber-color.jpg" width="150" height="150" class="img-responsive color" alt="Bumper Numbers">
				<h4>Bumper Numbers</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/resources-programming/" class="addcolor">
				<img src="/images/categories/resources-programming-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Programming Resources">
				<img src="/images/categories/resources-programming-color.jpg" width="150" height="150" class="img-responsive color" alt="Programming Resources">
				<h4>Programming Resources</h4>
			</a>
		</div>
		<div class="col-6 col-sm-4 col-md-3 placeholder">
			<a href="/vendors/" class="addcolor">
				<img src="/images/categories/vendor-gray.jpg" width="150" height="150" class="img-responsive gray" alt="Vendors">
				<img src="/images/categories/vendor-color.jpg" width="150" height="150" class="img-responsive color" alt="Vendors">
				<h4>Vendors</h4>
			</a>
		</div>
	</div>

