		<h1 class="page-header">Select pneumatic product</h1>
          <div class="row placeholders">
            <!--<div class="col-xs-6 col-md-3 placeholder">
              <a href="/pneumatics/accumulators" class="addcolor">
              	<img src="/images/airtank-gray.jpg" width="200" height="200" class="img-responsive gray" alt="Air Tanks">
              	<img src="/images/airtank-color.jpg" width="200" height="200" class="img-responsive color" alt="Air Tanks">
              	<h4>Air Tanks</h4>
              </a>
            </div>-->
            <div class="col-xs-6 col-md-3 placeholder">
              <a href="/pneumatics/compressors" class="addcolor">
              	<img src="/images/compressor-gray.jpg" width="200" height="200" class="img-responsive gray" alt="Compressors">
              	<img src="/images/compressor-color.jpg" width="200" height="200" class="img-responsive color" alt="Compressors">
              <h4>Compressors</h4>
              </a>
            </div>
          </div>